### ISSUE TITLE
Invalid ending tag in .xml file

### ISSUE THREAD

**Issue by techtwo** [cmdotcom-plugins/tracedock-magento2#2]
Hi,

When installing the module I get the folllowing error:

The XML in file "/var/www/html/vendor/tracedock/module-transaction-tracking/src/etc/adminhtml/system.xml" is invalid:
Warning: DOMDocument::loadXML(): Opening and ending tag mismatch: label line 19 and field in Entity

I think this is easily fixed by adding a "<" in the closing label tag on line 19 in system.xml

**Comment by ahmadjubair33** [comment]
Hi, @techtwo @cmdotcom-plugins I have fixed this error and raised a PR for the same please review and merge it.Thank you

**Comment by igorwulff** [comment]
Thanks for reporting this and for creating a PR. I've merged the PR and released 1.0.2.

**Comment by techtwo** [comment]
Thank you for fixing! :+1:
