### ISSUE TITLE
Support Multi store/website configuration

### ISSUE THREAD

**Issue by RaphaelBronsveld** [cmdotcom-plugins/tracedock-magento2#4]
Hi!

**Issue**
Current implementation does not support a multistore set-up. 

**How to reproduce**
Have a Magento installation with a minimum of 2 websites/storeviews, where you'd have 2 different API urls.

- Enable TraceDock Transaction Tracking module
- Enable Production Mode
- TraceDock API endpoint

Are all storeview scoped configuration options but nowhere in the code are they actually utilised this way.

**Expected Result**
A configuration with 2 websites having different API endpoints should be possible. Even with the default scoped configuration setting the module to "disabled".

**Comment by bbakalov** [comment]
Pull request created for this issue
https://github.com/cmdotcom-plugins/tracedock-magento2/pull/7

**Comment by bschellekens** [comment]
Pull request created and closed
