### ISSUE TITLE
Support for PHP 8.1 / Magento 2.4.4

### ISSUE THREAD

**Issue by pepijnblom** [cmdotcom-plugins/tracedock-magento2#5]
There's a PHP version constraint in the composer.json limiting its use to PHP 7.4. 
When can we expect a version compatible with PHP 8.1 / Magento 2.4.4?

**Comment by igorwulff** [comment]
Hi @pepijnblom , this should be resolved in the latest release (1.0.3): https://github.com/cmdotcom-plugins/tracedock-magento2/releases/tag/1.0.3

**Comment by pepijnblom** [comment]
Thanks for the update
