### ISSUE TITLE
Tracedock Event Payload incorrect

### ISSUE THREAD

**Issue by RaphaelBronsveld** [cmdotcom-plugins/tracedock-magento2#8]
**Issue**
The payload that gets send towards Tracedock is incorrect.

**Provided Solution**
Pull Request https://github.com/cmdotcom-plugins/tracedock-magento2/pull/9

**Expected Results**
- Stitching happens correctly following the masked quote id, also used in the dataLayer.
- Product prices include tax
- Products are properly processed.
- Configurables are not sent towards Tracedock.

**Comment by bschellekens** [comment]
Pull Request https://github.com/cmdotcom-plugins/tracedock-magento2/pull/9
